import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import NavBar from 'components/NavBar'
import ProjectDetails from 'components/ProjectDetails'
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" 
              content="Generated by create next app" />
        <meta name="viewport" 
              content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar/>
      <main className={styles.main}>
        <Image
               src="/images/HeadShot.png"
               alt="head shot"
               width={180}
               height={190} />
        <div className={styles.grid}>
          <ProjectDetails route=''
                          title='Memoizit'
                          description='Similar to memoization, this is an app that helps to keep track of the helpful things learned'
                          techStack='Tech Stack: nothing yet'/>
          <ProjectDetails route=''
                          title='Skull King'
                          description='This is a simple score keeper for a game called Skull King.'
                          techStack='Tech Stack: DynamoDb'/>
          <ProjectDetails route=''
                          title='3'
                          description='s'
                          techStack=''/>
          <ProjectDetails route=''
                          title='4'
                          description='a'
                          techStack=''/>
        </div>
      </main>
    </>
  )
}
