import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "components/NavBar";
import Projects from "@/components/Projects";
import AboutMe from "@/components/AboutMe";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
	return (
		<>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<NavBar />
			<main className={styles.main}>
				<AboutMe />
				<Projects />
			</main>
		</>
	);
}
