import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import s from '@/styles/globals'
import Header from 'components/NavBar'
import ProjectDetails from 'components/ProjectDetails'
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter()

  function goToMemoizit() {
    router.push("");
  }

  return (
    <>
      <Head>
        <title>Nate Widmer</title>
        <meta name="description" 
              content="Generated by create next app" />
        <meta name="viewport" 
              content="width=device-width, initial-scale=1" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <h1>

        </h1>
        <Image className={styles.logo}
               src="/images/HeadShot.png"
               alt="head shot"
               width={180}
               height={190}
               priority />

        <div className={styles.grid}>
          <ProjectDetails route=''
                          title='1'
                          description='just some random text to see what color'/>
          <ProjectDetails route=''
                          title='2'
                          description='f'/>
          <ProjectDetails route=''
                          title='3'
                          description='s'/>
          <ProjectDetails route=''
                          title='4'
                          description='a'/>
        </div>
      </main>
    </>
  )
}
